[project]
name = "ai-understandings"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "vector_db",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
