[project]
name = "vector-db"
version = "0.1.0"
description = "Learning implementation of vector database"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.5",
]
